source 'https://rubygems.org'

gem 'awesome_print'
gem 'fancy_irb'
gem 'git-issue'
gem 'herdic'
gem 'hirb'
gem 'interactive_editor'
gem 'octokit'
gem 'powder'
gem 'rails', '>= 4.0.0'
gem 'synx'
gem 'xcpretty'
