source 'https://rubygems.org'

gem 'awesome_print'
gem 'fancy_irb'
gem 'git-issue', '>= 0.9.2'
gem 'herdic'
gem 'hirb'
gem 'interactive_editor'
gem 'octokit'
gem 'powder'
gem 'rails', '>= 3.2.19'
gem 'synx', '>= 0.0.52'
gem 'xcpretty'
